export enum ApiErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_OTP = "INVALID_OTP",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOO_MANY_OTP_REQUESTS = "TOO_MANY_OTP_REQUESTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",

  // Contest errors
  CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND",
  CONTEST_NOT_ACTIVE = "CONTEST_NOT_ACTIVE",

  // Problem errors
  PROBLEM_NOT_FOUND = "PROBLEM_NOT_FOUND",
  QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND",

  // Submission errors
  ALREADY_SUBMITTED = "ALREADY_SUBMITTED",

  // Learn path errors
  UPLOAD_NO_FILE = "UPLOAD_NO_FILE",
  UPLOAD_TOO_LARGE = "UPLOAD_TOO_LARGE",
  UPLOAD_UNSUPPORTED_TYPE = "UPLOAD_UNSUPPORTED_TYPE",
  UPLOAD_NOT_CONFIGURED = "UPLOAD_NOT_CONFIGURED",
  UPLOAD_FAILED = "UPLOAD_FAILED",

  // Learn paths
  LEARN_PATH_NOT_FOUND = "LEARN_PATH_NOT_FOUND",
  LEARN_MODULE_NOT_FOUND = "LEARN_MODULE_NOT_FOUND",
  LEARN_LESSON_NOT_FOUND = "LEARN_LESSON_NOT_FOUND",
  LEARN_QUESTION_NOT_FOUND = "LEARN_QUESTION_NOT_FOUND",
  LEARN_QUESTION_DUPLICATE = "LEARN_QUESTION_DUPLICATE",
  LEARN_PROBLEM_IN_LIVE_CONTEST = "LEARN_PROBLEM_IN_LIVE_CONTEST",
  LEARN_PATH_NOT_PUBLISHABLE = "LEARN_PATH_NOT_PUBLISHABLE",
  LEARN_PATH_SLUG_TAKEN = "LEARN_PATH_SLUG_TAKEN",

  // General errors
  FORBIDDEN = "FORBIDDEN",
  INVALID_REQUEST = "INVALID_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
