export enum ApiErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_OTP = "INVALID_OTP",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOO_MANY_OTP_REQUESTS = "TOO_MANY_OTP_REQUESTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",

  // Contest errors
  CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND",
  CONTEST_NOT_ACTIVE = "CONTEST_NOT_ACTIVE",

  // Problem errors
  PROBLEM_NOT_FOUND = "PROBLEM_NOT_FOUND",
  QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND",

  // Submission errors
  ALREADY_SUBMITTED = "ALREADY_SUBMITTED",

  // General errors
  FORBIDDEN = "FORBIDDEN",
  INVALID_REQUEST = "INVALID_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  RUN_EXECUTION_FAILED = "RUN_EXECUTION_FAILED",
}
