export enum ApiErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_OTP = "INVALID_OTP",
  OTP_LOCKED = "OTP_LOCKED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOO_MANY_OTP_REQUESTS = "TOO_MANY_OTP_REQUESTS",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  PASSWORD_LOGIN_UNAVAILABLE = "PASSWORD_LOGIN_UNAVAILABLE",
  GOOGLE_EMAIL_UNVERIFIED = "GOOGLE_EMAIL_UNVERIFIED",
  OAUTH_STATE_INVALID = "OAUTH_STATE_INVALID",
  OAUTH_NOT_CONFIGURED = "OAUTH_NOT_CONFIGURED",
  OAUTH_CANCELLED = "OAUTH_CANCELLED",
  OAUTH_FAILED = "OAUTH_FAILED",

  // Contest errors
  CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND",
  CONTEST_NOT_ACTIVE = "CONTEST_NOT_ACTIVE",

  // Problem errors
  PROBLEM_NOT_FOUND = "PROBLEM_NOT_FOUND",
  QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND",

  // Submission errors
  ALREADY_SUBMITTED = "ALREADY_SUBMITTED",

  // Learn paths
  LEARN_PATH_NOT_FOUND = "LEARN_PATH_NOT_FOUND",
  LEARN_LESSON_NOT_FOUND = "LEARN_LESSON_NOT_FOUND",
  LEARN_QUESTION_NOT_FOUND = "LEARN_QUESTION_NOT_FOUND",
  LEARN_SELF_MARK_UNSUPPORTED = "LEARN_SELF_MARK_UNSUPPORTED",
  LEARN_CANNOT_UNMARK_VERIFIED = "LEARN_CANNOT_UNMARK_VERIFIED",
  ATTEMPT_DEADLINE_PASSED = "ATTEMPT_DEADLINE_PASSED",

  // General errors
  FORBIDDEN = "FORBIDDEN",
  INVALID_REQUEST = "INVALID_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  RUN_EXECUTION_FAILED = "RUN_EXECUTION_FAILED",
}
